import { invoke } from '@tauri-apps/api/core';
import { save } from '@tauri-apps/plugin-dialog';
import './style.css';

type View='Today'|'Projects'|'Manual Entry'|'Reports'|'Settings';
type Project={id:string;name:string;notes?:string|null;archived:boolean};
type Entry={id:string;project_id:string;project_name:string;date:string;start_time:string;end_time:string;duration_minutes:number;note?:string|null};
type Summary={project_id:string;project_name:string;duration_minutes:number};
const views:View[]=['Today','Projects','Manual Entry','Reports','Settings'];
const today=()=>new Date().toISOString().slice(0,10);
let current:View='Today', projects:Project[]=[], allProjects:Project[]=[], entries:Entry[]=[], summaries:Summary[]=[];
let editingProject:Project|null=null, editingEntry:Entry|null=null;

const app=document.querySelector<HTMLDivElement>('#app')!;
function h(m:number){return `${Math.floor(m/60)}h ${m%60}m`;}
async function call<T>(cmd:string,args:any={}):Promise<T>{try{return await invoke<T>(cmd,args)}catch(e){alert(String(e));throw e}}
async function load(){projects=await call('list_projects',{includeArchived:false}); allProjects=await call('list_projects',{includeArchived:true});}
async function loadRange(start=today(),end=today(),pid?:string){entries=await call('list_time_entries',{startDate:start,endDate:end,projectId:pid||null}); summaries=await call('get_summary',{startDate:start,endDate:end,projectId:pid||null});}
function shell(content:string){app.innerHTML=`<div class="window"><div class="titlebar"><div class="traffic"><span></span><span></span><span></span></div><b>Vire</b><code>v0.1 local</code></div><div class="shell"><aside><div class="brand"><div class="mark">V</div><div><strong>Vire</strong><small>Manual Mode</small></div></div><nav>${views.map(v=>`<button class="nav ${v===current?'active':''}" data-view="${v}">${v}</button>`).join('')}</nav><div class="status"><b>Manual Mode / Capture deferred</b><p>No automatic activity capture runs in v0.1.</p></div></aside><main>${content}</main></div></div>`;document.querySelectorAll<HTMLButtonElement>('.nav').forEach(b=>b.onclick=()=>{current=b.dataset.view as View;render();});}
function capture(){return `<section class="banner"><b>Manual Mode / Capture deferred</b><p>Automatic active-window, idle, screenshot, keystroke, browser, terminal, URL, and screen capture are not implemented. Add time manually; data stays local.</p></section>`}
function projectOptions(sel=''){return projects.map(p=>`<option value="${p.id}" ${p.id===sel?'selected':''}>${p.name}</option>`).join('')}
async function render(){await load(); if(current==='Today')return renderToday(); if(current==='Projects')return renderProjects(); if(current==='Manual Entry')return renderManual(); if(current==='Reports')return renderReports(); renderSettings();}
async function renderToday(){await loadRange(); shell(`${capture()}<header><h1>Today</h1><p>${today()}</p></header><div class="cards"><div class="card"><span>Total tracked</span><strong>${h(summaries.reduce((a,s)=>a+s.duration_minutes,0))}</strong></div>${summaries.map(s=>`<div class="card"><span>${s.project_name}</span><strong>${h(s.duration_minutes)}</strong></div>`).join('')||'<div class="empty">No manual entries today. Create a project, then add time in Manual Entry.</div>'}</div><h2>Today entries</h2>${table(entries)}`);}
function renderProjects(){shell(`<header><h1>Projects</h1><p>Create, edit, and archive local projects.</p></header><form id="projectForm" class="panel"><h2>${editingProject?'Edit project':'New project'}</h2><input name="name" placeholder="Project name" value="${editingProject?.name||''}" required><textarea name="notes" placeholder="Optional notes">${editingProject?.notes||''}</textarea><button>${editingProject?'Save project':'Create project'}</button>${editingProject?'<button type="button" id="cancelProject">Cancel</button>':''}</form><h2>All projects</h2><table><tr><th>Name</th><th>Notes</th><th>Status</th><th></th></tr>${allProjects.map(p=>`<tr><td>${p.name}</td><td>${p.notes||''}</td><td>${p.archived?'Archived':'Active'}</td><td><button data-editp="${p.id}">Edit</button> ${!p.archived?`<button data-archive="${p.id}" class="danger">Archive</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No projects yet.</td></tr>'}</table>`);bindProjects();}
function bindProjects(){document.querySelector<HTMLFormElement>('#projectForm')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input={name:String(f.get('name')),notes:String(f.get('notes')||'')}; if(editingProject) await call('update_project',{id:editingProject.id,input}); else await call('create_project',{input}); editingProject=null;render();};document.querySelector('#cancelProject')?.addEventListener('click',()=>{editingProject=null;render()});document.querySelectorAll<HTMLButtonElement>('[data-editp]').forEach(b=>b.onclick=()=>{editingProject=allProjects.find(p=>p.id===b.dataset.editp)!;renderProjects();});document.querySelectorAll<HTMLButtonElement>('[data-archive]').forEach(b=>b.onclick=async()=>{if(confirm('Archive this project? Historical entries remain reportable.')){await call('archive_project',{id:b.dataset.archive});render();}});}
async function renderManual(){const start=document.querySelector<HTMLInputElement>('#mStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#mEnd')?.value||today(); await loadRange(start,end); shell(`<header><h1>Manual Entry</h1><p>Add, edit, or deliberately delete manual time entries.</p></header><form id="entryForm" class="panel grid"><h2>${editingEntry?'Edit entry':'Add entry'}</h2><select name="project_id" required>${projectOptions(editingEntry?.project_id)}</select><input name="date" type="date" value="${editingEntry?.date||today()}" required><input name="start_time" type="time" value="${editingEntry?.start_time||'09:00'}" required><input name="end_time" type="time" value="${editingEntry?.end_time||'10:00'}" required><input name="note" placeholder="Optional note" value="${editingEntry?.note||''}"><button ${projects.length?'':'disabled'}>${editingEntry?'Save entry':'Add entry'}</button>${editingEntry?'<button type="button" id="cancelEntry">Cancel</button>':''}</form><div class="filters"><input id="mStart" type="date" value="${start}"><input id="mEnd" type="date" value="${end}"><button id="applyManual">Apply</button></div>${projects.length?'':'<p class="empty">Create an active project before adding entries.</p>'}<h2>Entries</h2>${table(entries,true)}`);bindEntries();}
function bindEntries(){document.querySelector<HTMLFormElement>('#entryForm')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input=Object.fromEntries(f.entries()); if(editingEntry) await call('update_time_entry',{id:editingEntry.id,input}); else await call('create_time_entry',{input}); editingEntry=null;renderManual();};document.querySelector('#cancelEntry')?.addEventListener('click',()=>{editingEntry=null;renderManual()});document.querySelector('#applyManual')?.addEventListener('click',()=>renderManual());document.querySelectorAll<HTMLButtonElement>('[data-edite]').forEach(b=>b.onclick=()=>{editingEntry=entries.find(e=>e.id===b.dataset.edite)!;renderManual();});document.querySelectorAll<HTMLButtonElement>('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this time entry? This cannot be undone.')){await call('delete_time_entry',{id:b.dataset.del});renderManual();}});}
async function renderReports(){const start=document.querySelector<HTMLInputElement>('#rStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#rEnd')?.value||today(); const pid=(document.querySelector<HTMLSelectElement>('#rProject')?.value)||''; await loadRange(start,end,pid); shell(`<header><h1>Reports</h1><p>Manual-entry totals grouped by project.</p></header><div class="filters"><input id="rStart" type="date" value="${start}"><input id="rEnd" type="date" value="${end}"><select id="rProject"><option value="">All active and historical projects</option>${allProjects.map(p=>`<option value="${p.id}" ${p.id===pid?'selected':''}>${p.name}${p.archived?' (archived)':''}</option>`).join('')}</select><button id="applyReports">Apply</button><button id="exportCsv">Export CSV…</button></div><div class="cards">${summaries.map(s=>`<div class="card"><span>${s.project_name}</span><strong>${h(s.duration_minutes)}</strong></div>`).join('')||'<div class="empty">No report data for this range.</div>'}</div><h2>Report entries</h2>${table(entries)}`);document.querySelector('#applyReports')!.addEventListener('click',()=>renderReports());document.querySelector('#exportCsv')!.addEventListener('click',async()=>{const dest=await save({filters:[{name:'CSV',extensions:['csv']}],defaultPath:'vire-report.csv'}); if(dest){const n=await call<number>('export_report_csv',{startDate:start,endDate:end,projectId:pid||null,destination:dest}); alert(`Exported ${n} entries.`);}});}
function renderSettings(){shell(`${capture()}<header><h1>Settings</h1><p>Local-only status and privacy.</p></header><section class="panel"><h2>Storage</h2><p>Vire v0.1 stores projects, manual entries, and minimal settings in a local SQLite database on this Mac. There are no accounts, cloud sync, hosted APIs, or network features.</p><h2>Capture status</h2><p>Automatic capture is deferred. This app does not collect screenshots, keystrokes, active windows, idle state, terminal commands, browser contents, full URLs, screen pixels, or file contents.</p></section>`)}
function table(rows:Entry[], actions=false){return `<table><tr><th>Date</th><th>Project</th><th>Start</th><th>End</th><th>Duration</th><th>Note</th>${actions?'<th></th>':''}</tr>${rows.map(e=>`<tr><td>${e.date}</td><td>${e.project_name}</td><td>${e.start_time}</td><td>${e.end_time}</td><td>${h(e.duration_minutes)}</td><td>${e.note||''}</td>${actions?`<td><button data-edite="${e.id}">Edit</button> <button class="danger" data-del="${e.id}">Delete</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${actions?7:6}" class="empty">No entries found.</td></tr>`}</table>`}
render();
