import { invoke } from '@tauri-apps/api/core';
import './style.css';
import { localDateInputValue } from './date';
import { optionalText } from './forms';
import { escapeHtml as esc } from './html';

type View='Today'|'Projects'|'Manual Entry'|'Reports'|'Settings';
type Project={id:string;name:string;notes?:string|null;archived:boolean};
type Entry={id:string;project_id:string;project_name:string;date:string;start_time:string;end_time:string;duration_minutes:number;note?:string|null};
type Summary={project_id:string;project_name:string;duration_minutes:number};
const views:View[]=['Today','Projects','Manual Entry','Reports','Settings'];
const today=()=>localDateInputValue();
let current:View='Today', projects:Project[]=[], allProjects:Project[]=[], entries:Entry[]=[], summaries:Summary[]=[];
let editingProject:Project|null=null, editingEntry:Entry|null=null, lastError='';

const app=document.querySelector<HTMLDivElement>('#app')!;
function h(m:number){return `${Math.floor(m/60)}h ${m%60}m`;}
function errorText(e:unknown){return e instanceof Error ? e.message : String(e);}
function setError(e:unknown){lastError=errorText(e); console.error(e);}
function alertError(e:unknown){setError(e); alert(lastError);}
function errorBanner(){return lastError?`<section class="banner danger-banner"><b>Action needed</b><p>${esc(lastError)}</p></section>`:''}
function rerender(){void render();}
function run(action:()=>Promise<void>){void action().catch(alertError)}
async function call<T>(cmd:string,args:any={}):Promise<T>{try{return await invoke<T>(cmd,args)}catch(e){throw new Error(errorText(e))}}
async function load(){projects=await call('list_projects',{includeArchived:false}); allProjects=await call('list_projects',{includeArchived:true});}
async function loadRange(start=today(),end=today(),pid?:string){entries=await call('list_time_entries',{startDate:start,endDate:end,projectId:pid||null}); summaries=await call('get_summary',{startDate:start,endDate:end,projectId:pid||null});}
function shell(content:string){app.innerHTML=`<div class="window"><div class="titlebar"><div class="traffic"><span></span><span></span><span></span></div><b>Vire</b><code>v0.1 local</code></div><div class="shell"><aside><div class="brand"><div class="mark">V</div><div><strong>Vire</strong><small>Manual Mode</small></div></div><nav>${views.map(v=>`<button class="nav ${v===current?'active':''}" data-view="${esc(v)}">${esc(v)}</button>`).join('')}</nav><div class="status"><b>Manual Mode / Capture deferred</b><p>No automatic activity capture runs in v0.1.</p></div></aside><main>${content}</main></div></div>`;document.querySelectorAll<HTMLButtonElement>('.nav').forEach(b=>b.onclick=()=>{current=b.dataset.view as View;rerender();});}
function capture(){return `<section class="banner"><b>Manual Mode / Capture deferred</b><p>Automatic active-window, idle, screenshot, keystroke, browser, terminal, URL, and screen capture are not implemented. Add time manually; data stays local.</p></section>`}
function projectOptions(sel=''){const opts=[...projects];const selected=allProjects.find(p=>p.id===sel);if(selected&&!opts.some(p=>p.id===selected.id))opts.push(selected);return opts.map(p=>`<option value="${esc(p.id)}" ${p.id===sel?'selected':''}>${esc(p.name)}${p.archived?' (archived)':''}</option>`).join('')}
async function render(){try{await load(); lastError=''; if(current==='Today')return await renderToday(); if(current==='Projects')return renderProjects(); if(current==='Manual Entry')return await renderManual(); if(current==='Reports')return await renderReports(); renderSettings();}catch(e){setError(e); shell(`${errorBanner()}<header><h1>${esc(current)}</h1><p>Vire could not load this view. Check the message above and try again.</p></header>`);}}
async function renderToday(){await loadRange(); shell(`${errorBanner()}${capture()}<header><h1>Today</h1><p>${esc(today())}</p></header><div class="cards"><div class="card"><span>Total tracked</span><strong>${esc(h(summaries.reduce((a,s)=>a+s.duration_minutes,0)))}</strong></div>${summaries.map(s=>`<div class="card"><span>${esc(s.project_name)}</span><strong>${esc(h(s.duration_minutes))}</strong></div>`).join('')||'<div class="empty">No manual entries today. Create a project, then add time in Manual Entry.</div>'}</div><h2>Today entries</h2>${table(entries)}`);}
function renderProjects(){shell(`${errorBanner()}<header><h1>Projects</h1><p>Create, edit, and archive local projects.</p></header><form id="projectForm" class="panel"><h2>${editingProject?'Edit project':'New project'}</h2><input name="name" maxlength="120" placeholder="Project name" value="${esc(editingProject?.name||'')}" required><textarea name="notes" maxlength="5000" placeholder="Optional notes">${esc(editingProject?.notes||'')}</textarea><button>${editingProject?'Save project':'Create project'}</button>${editingProject?'<button type="button" id="cancelProject">Cancel</button>':''}</form><h2>All projects</h2><table><tr><th>Name</th><th>Notes</th><th>Status</th><th></th></tr>${allProjects.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.notes||'')}</td><td>${p.archived?'Archived':'Active'}</td><td><button data-editp="${esc(p.id)}">Edit</button> ${!p.archived?`<button data-archive="${esc(p.id)}" class="danger">Archive</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No projects yet.</td></tr>'}</table>`);bindProjects();}
function bindProjects(){document.querySelector<HTMLFormElement>('#projectForm')!.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input={name:String(f.get('name')),notes:optionalText(f.get('notes'))}; if(editingProject) await call('update_project',{id:editingProject.id,input}); else await call('create_project',{input}); editingProject=null;rerender();});document.querySelector('#cancelProject')?.addEventListener('click',()=>{editingProject=null;rerender()});document.querySelectorAll<HTMLButtonElement>('[data-editp]').forEach(b=>b.onclick=()=>{editingProject=allProjects.find(p=>p.id===b.dataset.editp)!;renderProjects();});document.querySelectorAll<HTMLButtonElement>('[data-archive]').forEach(b=>b.onclick=()=>run(async()=>{if(confirm('Archive this project? Historical entries remain reportable.')){await call('archive_project',{id:b.dataset.archive});rerender();}}));}
async function renderManual(){const start=document.querySelector<HTMLInputElement>('#mStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#mEnd')?.value||today(); await loadRange(start,end); shell(`${errorBanner()}<header><h1>Manual Entry</h1><p>Add, edit, or deliberately delete manual time entries.</p></header><form id="entryForm" class="panel grid"><h2>${editingEntry?'Edit entry':'Add entry'}</h2><select name="project_id" required>${projectOptions(editingEntry?.project_id)}</select><input name="date" type="date" value="${esc(editingEntry?.date||today())}" required><input name="start_time" type="time" value="${esc(editingEntry?.start_time||'09:00')}" required><input name="end_time" type="time" value="${esc(editingEntry?.end_time||'10:00')}" required><input name="note" maxlength="2000" placeholder="Optional note" value="${esc(editingEntry?.note||'')}"><button ${(projects.length||editingEntry)?'':'disabled'}>${editingEntry?'Save entry':'Add entry'}</button>${editingEntry?'<button type="button" id="cancelEntry">Cancel</button>':''}</form><div class="filters"><input id="mStart" type="date" value="${esc(start)}"><input id="mEnd" type="date" value="${esc(end)}"><button id="applyManual">Apply</button></div>${projects.length||editingEntry?'':'<p class="empty">Create an active project before adding entries.</p>'}<h2>Entries</h2>${table(entries,true)}`);bindEntries();}
function bindEntries(){document.querySelector<HTMLFormElement>('#entryForm')!.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input={project_id:String(f.get('project_id')),date:String(f.get('date')),start_time:String(f.get('start_time')),end_time:String(f.get('end_time')),note:optionalText(f.get('note'))}; if(editingEntry) await call('update_time_entry',{id:editingEntry.id,input}); else await call('create_time_entry',{input}); editingEntry=null;await renderManual();});document.querySelector('#cancelEntry')?.addEventListener('click',()=>{editingEntry=null;run(renderManual)});document.querySelector('#applyManual')?.addEventListener('click',()=>run(renderManual));document.querySelectorAll<HTMLButtonElement>('[data-edite]').forEach(b=>b.onclick=()=>{editingEntry=entries.find(e=>e.id===b.dataset.edite)!;run(renderManual);});document.querySelectorAll<HTMLButtonElement>('[data-del]').forEach(b=>b.onclick=()=>run(async()=>{if(confirm('Delete this time entry? This cannot be undone.')){await call('delete_time_entry',{id:b.dataset.del});await renderManual();}}));}
async function renderReports(){const start=document.querySelector<HTMLInputElement>('#rStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#rEnd')?.value||today(); const pid=(document.querySelector<HTMLSelectElement>('#rProject')?.value)||''; await loadRange(start,end,pid); shell(`${errorBanner()}<header><h1>Reports</h1><p>Manual-entry totals grouped by project.</p></header><div class="filters"><input id="rStart" type="date" value="${esc(start)}"><input id="rEnd" type="date" value="${esc(end)}"><select id="rProject"><option value="">All active and historical projects</option>${allProjects.map(p=>`<option value="${esc(p.id)}" ${p.id===pid?'selected':''}>${esc(p.name)}${p.archived?' (archived)':''}</option>`).join('')}</select><button id="applyReports">Apply</button><button id="exportCsv">Export CSV…</button></div><div class="cards">${summaries.map(s=>`<div class="card"><span>${esc(s.project_name)}</span><strong>${esc(h(s.duration_minutes))}</strong></div>`).join('')||'<div class="empty">No report data for this range.</div>'}</div><h2>Report entries</h2>${table(entries)}`);document.querySelector('#applyReports')!.addEventListener('click',()=>run(renderReports));document.querySelector('#exportCsv')!.addEventListener('click',()=>run(async()=>{const n=await call<number|null>('export_report_csv',{startDate:start,endDate:end,projectId:pid||null}); if(n!==null) alert(`Exported ${n} entries.`);}));}
function renderSettings(){shell(`${errorBanner()}${capture()}<header><h1>Settings</h1><p>Local-only status and privacy.</p></header><section class="panel"><h2>Storage</h2><p>Vire v0.1 stores projects, manual entries, and minimal settings in a local SQLite database on this Mac. There are no accounts, cloud sync, hosted APIs, or network features.</p><h2>Capture status</h2><p>Automatic capture is deferred. This app does not collect screenshots, keystrokes, active windows, idle state, terminal commands, browser contents, full URLs, screen pixels, or file contents.</p></section>`)}
function table(rows:Entry[], actions=false){return `<table><tr><th>Date</th><th>Project</th><th>Start</th><th>End</th><th>Duration</th><th>Note</th>${actions?'<th></th>':''}</tr>${rows.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.project_name)}</td><td>${esc(e.start_time)}</td><td>${esc(e.end_time)}</td><td>${esc(h(e.duration_minutes))}</td><td>${esc(e.note||'')}</td>${actions?`<td><button data-edite="${esc(e.id)}">Edit</button> <button class="danger" data-del="${esc(e.id)}">Delete</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${actions?7:6}" class="empty">No entries found.</td></tr>`}</table>`}
rerender();
