import { invoke } from '@tauri-apps/api/core';
import './style.css';
import { localDateInputValue } from './date';
import { optionalText } from './forms';
import { escapeHtml as esc } from './html';
import { CUSTOM_RANGE_PRESET, DEFAULT_IMPORT_RANGE, IMPORT_RANGE_PRESETS, canonicalImportRange, importRangeLabel, parseImportRangeControl, secretStateLabel, testConnectionDisabledReason } from './langfuse-settings';
import { titlebar } from './shell-chrome';
import { type DiscoveredEnvState, envPickerCheckboxes, mappingPanel, mergeSelectedEnvironments } from './env-mapping-ui';
import { type ImportMode, type ImportReport, renderImportReport } from './import-report';
import { type SuggestionList, suggestionsBody } from './suggestions-ui';
import { summaryCards } from './summary-cards';
import { nextScrollTop } from './scroll';
import { REPORT_RANGE_PRESETS, reportRange } from './report-ranges';
import { type UpdateCheckResult, updateCheckPanel } from './update-check-ui';

type View='Today'|'Projects'|'Manual Entry'|'Reports'|'Suggestions'|'Settings';
type Project={id:string;name:string;notes?:string|null;archived:boolean};
// origin/cost_* are carried for completeness (DEC-003 / TASK-034 B); cost is null for manual entries and
// null-when-unknown for AI entries (absence ≠ zero → render "—"). Row rendering of cost is deferred.
type Entry={id:string;project_id:string;project_name:string;date:string;start_time:string;end_time:string;duration_minutes:number;note?:string|null;origin?:string;cost_total?:number|null;cost_currency?:string|null};
// duration_minutes is human/manual time only; ai_minutes is accepted AI-suggested time kept distinct so
// AI time is never folded into the billable human total (DEC-003 / TASK-032 B4). ai_cost_* mirror the
// backend SummaryRow cost fields (TASK-034 B); null → "—". Cards render this on the AI-suggested sub-line (summary-cards.ts, B5).
type Summary={project_id:string;project_name:string;duration_minutes:number;ai_minutes:number;ai_cost_total?:number|null;ai_cost_currency?:string|null};
type SourceHealth={base_url:string;source:string;environments:string[];last_import_at:string|null;latest_trace_ts:string|null;health:string;message:string};
type ImportOutcome={snapshot:SourceHealth;report:ImportReport|null};
type LangfuseSettings={base_url:string;source:string;environments:string[];langfuse_enabled:boolean;has_public_key:boolean;has_secret_key:boolean};
type TestConnectionResult={ok:boolean;verdict:string;message:string};
type RuntimeReconciliation={runtime_log_present:boolean;source:string;observed_runs:number;matched:number;observed_no_trace:number;unmatched_runtime:number;reconciliation_unknown:number;unmatched_trace:number;message:string};
const views:View[]=['Today','Projects','Manual Entry','Reports','Suggestions','Settings'];
const today=()=>localDateInputValue();
let current:View='Today', projects:Project[]=[], allProjects:Project[]=[], entries:Entry[]=[], summaries:Summary[]=[];
let editingProject:Project|null=null, editingEntry:Entry|null=null, lastError='', sourceHealth:SourceHealth|null=null, runtimeRecon:RuntimeReconciliation|null=null;
let langfuseSettings:LangfuseSettings|null=null, testConnResult:TestConnectionResult|null=null, lastImportReport:ImportReport|null=null, lastImportMode:ImportMode='incremental', langfuseImportRange:string=DEFAULT_IMPORT_RANGE, discoveredEnvs:DiscoveredEnvState[]=[];
let updateCheckState:UpdateCheckResult|null=null, updateCheckPending=false;
// Last view shell() rendered. Used to keep the user's scroll position across same-view re-renders and
// reset to the top on a view change (TASK-031). null = nothing rendered yet → first render starts at top.
let lastRenderedView:View|null=null;
const degradedHealth=['unavailable','stale','unknown','auth_or_network_error'];

const app=document.querySelector<HTMLDivElement>('#app')!;
function h(m:number){return `${Math.floor(m/60)}h ${m%60}m`;}
function errorText(e:unknown){return e instanceof Error ? e.message : String(e);}
function setError(e:unknown){lastError=errorText(e); console.error(e);}
function alertError(e:unknown){setError(e); alert(lastError);}
function errorBanner(){return lastError?`<section class="banner danger-banner"><b>Action needed</b><p>${esc(lastError)}</p></section>`:''}
function rerender(){void render();}
function run(action:()=>Promise<void>){void action().catch(alertError)}
async function call<T>(cmd:string,args:any={}):Promise<T>{try{return await invoke<T>(cmd,args)}catch(e){throw new Error(errorText(e))}}
async function load(){projects=await call('list_projects',{includeArchived:false}); allProjects=await call('list_projects',{includeArchived:true}); try{sourceHealth=await call<SourceHealth>('get_langfuse_source_health');}catch{sourceHealth=null;}}
function sourceBanner(){if(!sourceHealth||!degradedHealth.includes(sourceHealth.health))return ''; return `<section class="banner danger-banner"><b>AI evidence source: ${esc(sourceHealth.health)}</b><p>${esc(sourceHealth.message)}</p></section>`;}
async function loadRange(start=today(),end=today(),pid?:string){entries=await call('list_time_entries',{startDate:start,endDate:end,projectId:pid||null}); summaries=await call('get_summary',{startDate:start,endDate:end,projectId:pid||null});}
function shell(content:string){const prevScroll=app.querySelector('main')?.scrollTop??0;const sameView=lastRenderedView===current;app.innerHTML=`<div class="window">${titlebar('Vire','v0.1 local')}<div class="shell"><aside><div class="brand"><div class="mark">V</div><div><strong>Vire</strong><small>Manual Mode</small></div></div><nav>${views.map(v=>`<button class="nav ${v===current?'active':''}" data-view="${esc(v)}">${esc(v)}</button>`).join('')}</nav><div class="status"><b>Manual Mode / Capture deferred</b><p>No automatic activity capture runs in v0.1.</p></div></aside><main>${content}</main></div></div>`;const m=app.querySelector('main');if(m)m.scrollTop=nextScrollTop(sameView,prevScroll);lastRenderedView=current;document.querySelectorAll<HTMLButtonElement>('.nav').forEach(b=>b.onclick=()=>{current=b.dataset.view as View;rerender();});}
function capture(){return `<section class="banner"><b>Manual Mode / Capture deferred</b><p>Automatic active-window, idle, screenshot, keystroke, browser, terminal, URL, and screen capture are not implemented. Add time manually; data stays local.</p></section>`}
function projectOptions(sel=''){const opts=[...projects];const selected=allProjects.find(p=>p.id===sel);if(selected&&!opts.some(p=>p.id===selected.id))opts.push(selected);return opts.map(p=>`<option value="${esc(p.id)}" ${p.id===sel?'selected':''}>${esc(p.name)}${p.archived?' (archived)':''}</option>`).join('')}
async function render(){try{await load(); lastError=''; if(current==='Today')return await renderToday(); if(current==='Projects')return renderProjects(); if(current==='Manual Entry')return await renderManual(); if(current==='Reports')return await renderReports(); if(current==='Suggestions')return await renderSuggestions(); return await renderSettings();}catch(e){setError(e); shell(`${errorBanner()}<header><h1>${esc(current)}</h1><p>Vire could not load this view. Check the message above and try again.</p></header>`);}}
// Project summary cards live in ./summary-cards (pure, unit-tested). Human (origin='manual') time is
// the headline figure; accepted AI-suggested time and its cost are shown on a separate sub-line and
// never folded into the total, so prior numbers never shift (DEC-003 / TASK-032 B4 / TASK-034 B5).
async function renderToday(){await loadRange(); shell(`${errorBanner()}${sourceBanner()}${capture()}<header><h1>Today</h1><p>${esc(today())}</p></header>${summaryCards(summaries,true,'No manual entries today. Create a project, then add time in Manual Entry.')}<h2>Today entries</h2>${table(entries)}`);}
function renderProjects(){shell(`${errorBanner()}<header><h1>Projects</h1><p>Create, edit, and archive local projects.</p></header><form id="projectForm" class="panel"><h2>${editingProject?'Edit project':'New project'}</h2><input name="name" maxlength="120" placeholder="Project name" value="${esc(editingProject?.name||'')}" required><textarea name="notes" maxlength="5000" placeholder="Optional notes">${esc(editingProject?.notes||'')}</textarea><button>${editingProject?'Save project':'Create project'}</button>${editingProject?'<button type="button" id="cancelProject">Cancel</button>':''}</form><h2>All projects</h2><table><tr><th>Name</th><th>Notes</th><th>Status</th><th></th></tr>${allProjects.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.notes||'')}</td><td>${p.archived?'Archived':'Active'}</td><td><button data-editp="${esc(p.id)}">Edit</button> ${!p.archived?`<button data-archive="${esc(p.id)}" class="danger">Archive</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No projects yet.</td></tr>'}</table>`);bindProjects();}
function bindProjects(){document.querySelector<HTMLFormElement>('#projectForm')!.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input={name:String(f.get('name')),notes:optionalText(f.get('notes'))}; if(editingProject) await call('update_project',{id:editingProject.id,input}); else await call('create_project',{input}); editingProject=null;rerender();});document.querySelector('#cancelProject')?.addEventListener('click',()=>{editingProject=null;rerender()});document.querySelectorAll<HTMLButtonElement>('[data-editp]').forEach(b=>b.onclick=()=>{editingProject=allProjects.find(p=>p.id===b.dataset.editp)!;renderProjects();});document.querySelectorAll<HTMLButtonElement>('[data-archive]').forEach(b=>b.onclick=()=>run(async()=>{if(confirm('Archive this project? Historical entries remain reportable.')){await call('archive_project',{id:b.dataset.archive});rerender();}}));}
async function renderManual(){const start=document.querySelector<HTMLInputElement>('#mStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#mEnd')?.value||today(); await loadRange(start,end); shell(`${errorBanner()}<header><h1>Manual Entry</h1><p>Add, edit, or deliberately delete manual time entries.</p></header><form id="entryForm" class="panel grid"><h2>${editingEntry?'Edit entry':'Add entry'}</h2><select name="project_id" required>${projectOptions(editingEntry?.project_id)}</select><input name="date" type="date" value="${esc(editingEntry?.date||today())}" required><input name="start_time" type="time" value="${esc(editingEntry?.start_time||'09:00')}" required><input name="end_time" type="time" value="${esc(editingEntry?.end_time||'10:00')}" required><input name="note" maxlength="2000" placeholder="Optional note" value="${esc(editingEntry?.note||'')}"><button ${(projects.length||editingEntry)?'':'disabled'}>${editingEntry?'Save entry':'Add entry'}</button>${editingEntry?'<button type="button" id="cancelEntry">Cancel</button>':''}</form><div class="filters"><input id="mStart" type="date" value="${esc(start)}"><input id="mEnd" type="date" value="${esc(end)}"><button id="applyManual">Apply</button></div>${projects.length||editingEntry?'':'<p class="empty">Create an active project before adding entries.</p>'}<h2>Entries</h2>${table(entries,true)}`);bindEntries();}
function bindEntries(){document.querySelector<HTMLFormElement>('#entryForm')!.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const input={project_id:String(f.get('project_id')),date:String(f.get('date')),start_time:String(f.get('start_time')),end_time:String(f.get('end_time')),note:optionalText(f.get('note'))}; if(editingEntry) await call('update_time_entry',{id:editingEntry.id,input}); else await call('create_time_entry',{input}); editingEntry=null;await renderManual();});document.querySelector('#cancelEntry')?.addEventListener('click',()=>{editingEntry=null;run(renderManual)});document.querySelector('#applyManual')?.addEventListener('click',()=>run(renderManual));document.querySelectorAll<HTMLButtonElement>('[data-edite]').forEach(b=>b.onclick=()=>{editingEntry=entries.find(e=>e.id===b.dataset.edite)!;run(renderManual);});document.querySelectorAll<HTMLButtonElement>('[data-del]').forEach(b=>b.onclick=()=>run(async()=>{if(confirm('Delete this time entry? This cannot be undone.')){await call('delete_time_entry',{id:b.dataset.del});await renderManual();}}));}
async function renderReports(){const start=document.querySelector<HTMLInputElement>('#rStart')?.value||today(); const end=document.querySelector<HTMLInputElement>('#rEnd')?.value||today(); const pid=(document.querySelector<HTMLSelectElement>('#rProject')?.value)||''; await loadRange(start,end,pid); const rangeRow=`<div class="filters">${REPORT_RANGE_PRESETS.map(p=>{const r=reportRange(p.days);return `<button data-range="${esc(p.key)}"${r.start===start&&r.end===end?' aria-pressed="true"':''}>${esc(p.label)}</button>`;}).join('')}</div>`; shell(`${errorBanner()}<header><h1>Reports</h1><p>Manual-entry totals grouped by project.</p></header>${rangeRow}<div class="filters"><input id="rStart" type="date" value="${esc(start)}"><input id="rEnd" type="date" value="${esc(end)}"><select id="rProject"><option value="">All active and historical projects</option>${allProjects.map(p=>`<option value="${esc(p.id)}" ${p.id===pid?'selected':''}>${esc(p.name)}${p.archived?' (archived)':''}</option>`).join('')}</select><button id="applyReports">Apply</button><button id="exportCsv">Export CSV…</button></div>${summaryCards(summaries,false,'No report data for this range.')}<h2>Report entries</h2>${table(entries)}`);document.querySelectorAll<HTMLButtonElement>('[data-range]').forEach(b=>b.addEventListener('click',()=>{const p=REPORT_RANGE_PRESETS.find(x=>x.key===b.dataset.range);if(!p)return;const{start:s,end:e}=reportRange(p.days);const si=document.querySelector<HTMLInputElement>('#rStart');const ei=document.querySelector<HTMLInputElement>('#rEnd');if(si)si.value=s;if(ei)ei.value=e;run(renderReports);}));document.querySelector('#applyReports')!.addEventListener('click',()=>run(renderReports));document.querySelector('#exportCsv')!.addEventListener('click',()=>run(async()=>{const n=await call<number|null>('export_report_csv',{startDate:start,endDate:end,projectId:pid||null}); if(n!==null) alert(`Exported ${n} entries.`);}));}
// AI time-suggestion review (TASK-032 C). Loads the stored pending set (regenerate=false); the Refresh
// button recomputes from the latest evidence (regenerate=true) before re-rendering. Render is secret-free
// (suggestions-ui.ts); accept is the only path that posts a time entry (DEC-006).
async function renderSuggestions(){const list=await call<SuggestionList>('list_time_entry_suggestions',{regenerate:false}); const sourceDisabled=sourceHealth?.health==='disabled'; const sourceDegraded=!!sourceHealth&&(degradedHealth.includes(sourceHealth.health)||sourceDisabled); shell(`${errorBanner()}${sourceBanner()}${suggestionsBody(list,{sourceDegraded,sourceDisabled})}`); bindSuggestions();}
// Collect the inline edit-panel fields for a suggestion. Empty fields become null (no override). For an
// untimed block the backend requires start/end and returns a clear, secret-free error if absent — that
// error surfaces via run()/alertError rather than being re-validated here.
function editsFor(id:string){const panel=document.querySelector<HTMLElement>(`[data-edit-panel="${CSS.escape(id)}"]`);const get=(f:string)=>panel?.querySelector<HTMLInputElement>(`[data-edit-field="${f}"]`)?.value??'';return{date:get('date')||null,start_time:get('start_time')||null,end_time:get('end_time')||null,note:optionalText(get('note'))};}
function bindSuggestions(){document.querySelector('#refreshSuggestions')?.addEventListener('click',()=>run(async()=>{await call('list_time_entry_suggestions',{regenerate:true});await renderSuggestions();}));document.querySelectorAll<HTMLButtonElement>('[data-goto-view]').forEach(b=>b.onclick=()=>{current=b.dataset.gotoView as View;rerender();});document.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b=>b.onclick=()=>{const panel=document.querySelector<HTMLElement>(`[data-edit-panel="${CSS.escape(b.dataset.edit!)}"]`);if(panel)panel.hidden=!panel.hidden;});document.querySelectorAll<HTMLButtonElement>('[data-accept]').forEach(b=>b.onclick=()=>run(async()=>{await call('accept_time_entry_suggestion',{id:b.dataset.accept});await renderSuggestions();}));document.querySelectorAll<HTMLButtonElement>('[data-accept-edited]').forEach(b=>b.onclick=()=>run(async()=>{const id=b.dataset.acceptEdited!;await call('accept_time_entry_suggestion',{id,edits:editsFor(id)});await renderSuggestions();}));document.querySelectorAll<HTMLButtonElement>('[data-dismiss]').forEach(b=>b.onclick=()=>run(async()=>{if(confirm('Dismiss this suggestion? It posts no time entry and will not reappear on refresh.')){await call('dismiss_time_entry_suggestion',{id:b.dataset.dismiss});await renderSuggestions();}}));}
async function renderSettings(){try{runtimeRecon=await call<RuntimeReconciliation>('get_runtime_reconciliation');}catch{runtimeRecon=null;} try{langfuseSettings=await call<LangfuseSettings>('get_langfuse_settings');}catch{langfuseSettings=null;} try{discoveredEnvs=await call<DiscoveredEnvState[]>('list_discovered_environments');}catch{discoveredEnvs=[];} try{langfuseImportRange=await call<string>('get_langfuse_import_range');}catch{langfuseImportRange=DEFAULT_IMPORT_RANGE;} shell(`${errorBanner()}${sourceBanner()}${capture()}<header><h1>Settings</h1><p>Local-only status and privacy.</p></header><section class="panel"><h2>Storage</h2><p>Vire v0.1 stores projects, manual entries, and minimal settings in a local SQLite database on this Mac. There are no accounts, cloud sync, hosted APIs, or network features.</p><h2>Capture status</h2><p>Automatic capture is deferred. This app does not collect screenshots, keystrokes, active windows, idle state, terminal commands, browser contents, full URLs, screen pixels, or file contents.</p></section>${updateCheckPanel(updateCheckState,updateCheckPending)}${langfusePanel()}${sourcePanel()}${mappingPanel(discoveredEnvs,projects)}`);bindImportControls();bindLangfuse();bindEnvMapping();bindUpdateCheck();}
function bindUpdateCheck(){
  document.querySelector('#checkForUpdates')?.addEventListener('click',()=>{
    if(updateCheckPending)return;
    updateCheckPending=true;
    document.querySelector<HTMLButtonElement>('#checkForUpdates')!.disabled=true;
    document.querySelector<HTMLButtonElement>('#checkForUpdates')!.textContent='Checking…';
    void call<UpdateCheckResult>('check_for_update').then(r=>{updateCheckState=r;updateCheckPending=false;if(current==='Settings')void renderSettings();}).catch(e=>{updateCheckState={status:'unknown',reason:errorText(e)};updateCheckPending=false;if(current==='Settings')void renderSettings();});
  });
  document.querySelector('#openReleasesPage')?.addEventListener('click',()=>run(async()=>{await call('open_releases_page');}));
  document.querySelector<HTMLButtonElement>('#openReleasesSpecific')?.addEventListener('click',e=>{run(async()=>{await call('open_releases_page');});});
}
// Import/backfill/range controls (TASK-029 D). Each import button disables both buttons and shows
// progress text while in flight, then rerenders (which re-enables them). The range form canonicalizes
// the picker selection before persisting; the backend re-validates and returns the canonical value.
function runImport(cmd:string,mode:ImportMode,btn:HTMLButtonElement,busyLabel:string){const other=btn.id==='importLangfuse'?'#backfillLangfuse':'#importLangfuse';const otherBtn=document.querySelector<HTMLButtonElement>(other);btn.disabled=true;btn.textContent=busyLabel;if(otherBtn)otherBtn.disabled=true;void(async()=>{try{const out=await call<ImportOutcome>(cmd);sourceHealth=out.snapshot;lastImportReport=out.report;lastImportMode=mode;}catch(e){alertError(e);}rerender();})();}
function bindImportControls(){document.querySelector<HTMLButtonElement>('#importLangfuse')?.addEventListener('click',e=>runImport('import_langfuse_now','incremental',e.currentTarget as HTMLButtonElement,'Importing…'));document.querySelector<HTMLButtonElement>('#backfillLangfuse')?.addEventListener('click',e=>runImport('backfill_langfuse_now','backfill',e.currentTarget as HTMLButtonElement,'Backfilling…'));const preset=document.querySelector<HTMLSelectElement>('#langfuseRangePreset');const since=document.querySelector<HTMLElement>('#langfuseSince');if(preset&&since)preset.addEventListener('change',()=>{since.hidden=preset.value!==CUSTOM_RANGE_PRESET;});const rangeForm=document.querySelector<HTMLFormElement>('#langfuseRangeForm');if(rangeForm)rangeForm.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const presetVal=String(f.get('range_preset')||DEFAULT_IMPORT_RANGE);const sinceVal=String(f.get('since_date')||'');if(presetVal===CUSTOM_RANGE_PRESET&&!sinceVal){alert('Pick a date for the custom import range.');return;}langfuseImportRange=await call<string>('set_langfuse_import_range',{range:canonicalImportRange(presetVal,sinceVal)});rerender();});}
function langfusePanel(){const s=langfuseSettings; if(!s) return `<section class="panel"><h2>Langfuse integration</h2><p>Settings are unavailable. Reopen Settings to retry.</p></section>`; const hasCreds=s.has_public_key||s.has_secret_key; const t=testConnResult; const testLine=t?`<p class="test-result ${t.ok?'ok':'fail'}">Test connection: <b>${esc(t.verdict)}</b> — ${esc(t.message)}</p>`:''; return `<section class="panel"><h2>Langfuse integration</h2><p>Configure how Vire imports AI evidence (time, usage, and cost) from your local Langfuse. Vire only reads Langfuse traces — it never emits them.</p><form id="langfuseForm" class="lf-form"><label class="switch"><input type="checkbox" name="enabled" ${s.langfuse_enabled?'checked':''}><span>Enable AI evidence import</span></label><label>Base URL<input name="base_url" value="${esc(s.base_url)}" placeholder="http://127.0.0.1:3000" required></label><label>Source<select name="source"><option value="local" ${s.source==='local'?'selected':''}>Local (Docker, loopback)</option><option value="cloud" ${s.source==='cloud'?'selected':''}>Cloud (explicit override)</option></select></label><fieldset class="env-picker"><legend>Environments to import</legend><p class="hint">Pick the Langfuse environments Vire imports. Discovered environments appear automatically after an import; <code>vire</code> is the default.</p>${envPickerCheckboxes(discoveredEnvs.map(d=>d.environment),s.environments)}<details class="env-advanced"><summary>Advanced — add an environment manually</summary><label>Comma-separated (for environments not yet discovered)<input name="environments" value="" placeholder="staging, prod"></label></details></fieldset><button>Save settings</button></form><h3>Credentials</h3><p>Public key: <b>${secretStateLabel(s.has_public_key)}</b> · Secret key: <b>${secretStateLabel(s.has_secret_key)}</b>. The secret key is stored in the macOS Keychain and is never displayed back.</p><form id="langfuseSecretForm" class="lf-form"><label>Public key<input name="public_key" autocomplete="off" placeholder="pk-lf-…"></label><label>Secret key<input name="secret_key" type="password" autocomplete="off" placeholder="sk-lf-…"></label><div class="row"><button>${hasCreds?'Replace credentials':'Save credentials'}</button>${hasCreds?'<button type="button" id="langfuseClear" class="danger">Clear credentials</button>':''}</div></form><h3>Test connection</h3><div class="row"><button id="langfuseTest" ${(()=>{const r=testConnectionDisabledReason(s.langfuse_enabled);return r?`disabled title="${esc(r)}"`:'';})()}>Test connection</button></div><div aria-live="polite">${testLine}</div></section>`}
function bindLangfuse(){const form=document.querySelector<HTMLFormElement>('#langfuseForm');if(form)form.onsubmit=e=>run(async()=>{e.preventDefault();const el=e.currentTarget as HTMLFormElement;const f=new FormData(el);const picked=[...el.querySelectorAll<HTMLInputElement>('input[name="env_pick"]:checked')].map(i=>i.value);const input={base_url:String(f.get('base_url')||'').trim(),source:String(f.get('source')||'local'),environments:mergeSelectedEnvironments(picked,String(f.get('environments')||'')),langfuse_enabled:f.get('enabled')!==null};langfuseSettings=await call<LangfuseSettings>('set_langfuse_settings',{input});testConnResult=null;rerender();});const secretForm=document.querySelector<HTMLFormElement>('#langfuseSecretForm');if(secretForm)secretForm.onsubmit=e=>run(async()=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const publicKey=String(f.get('public_key')||'').trim();const secretKey=String(f.get('secret_key')||'').trim();await call('set_langfuse_secret',{publicKey,secretKey});testConnResult=null;rerender();});document.querySelector('#langfuseClear')?.addEventListener('click',()=>run(async()=>{if(confirm('Clear the stored Langfuse credentials from the macOS Keychain?')){await call('clear_langfuse_secret');testConnResult=null;rerender();}}));document.querySelector('#langfuseTest')?.addEventListener('click',()=>run(async()=>{testConnResult=await call<TestConnectionResult>('test_langfuse_connection');rerender();}));}
function bindEnvMapping(){document.querySelectorAll<HTMLButtonElement>('[data-map-set]').forEach(b=>b.onclick=()=>run(async()=>{const env=b.dataset.mapSet!;const sel=document.querySelector<HTMLSelectElement>(`[data-map-select="${CSS.escape(env)}"]`);const projectId=sel?.value||'';if(!projectId){alert('Choose a project to map this environment to.');return;}await call('set_env_mapping',{environment:env,projectId});rerender();}));document.querySelectorAll<HTMLButtonElement>('[data-clear-map]').forEach(b=>b.onclick=()=>run(async()=>{const env=b.dataset.clearMap!;if(confirm(`Clear the project mapping for environment "${env}"? Imported evidence is untouched — only the link changes.`)){await call('clear_env_mapping',{environment:env});rerender();}}));document.querySelectorAll<HTMLButtonElement>('[data-create-map]').forEach(b=>b.onclick=()=>run(async()=>{const env=b.dataset.createMap!;const nameInput=document.querySelector<HTMLInputElement>(`[data-create-name="${CSS.escape(env)}"]`);const trimmed=(nameInput?.value||'').trim();if(!trimmed){alert('Project name cannot be empty.');nameInput?.focus();return;}const created=await call<Project>('create_project',{input:{name:trimmed,notes:null}});await call('set_env_mapping',{environment:env,projectId:created.id});rerender();}));}
function runtimeLine(){const r=runtimeRecon; if(!r)return ''; if(!r.runtime_log_present)return `<p>Runtime reconciliation: <b>unknown</b> — no runtime session log found. A down or absent source is unknown, never zero AI usage or cost.</p>`; return `<p>Observed agent runs: <b>${r.observed_runs}</b> · without a matching trace: <b>${r.observed_no_trace}</b> · unknown: <b>${r.reconciliation_unknown}</b>. A down or absent import is reported as unknown, never zero.</p>`}
function rangeControl(){const rc=parseImportRangeControl(langfuseImportRange); const opts=IMPORT_RANGE_PRESETS.map(p=>`<option value="${esc(p.value)}" ${p.value===rc.preset?'selected':''}>${esc(p.label)}</option>`).join(''); return `<form id="langfuseRangeForm" class="lf-form lf-range"><label>Import range<select id="langfuseRangePreset" name="range_preset">${opts}</select></label><label id="langfuseSince" ${rc.preset===CUSTOM_RANGE_PRESET?'':'hidden'}>Since date<input type="date" name="since_date" value="${esc(rc.sinceDate)}"></label><button>Save range</button></form><p class="hint">Current range: <b>${esc(importRangeLabel(langfuseImportRange))}</b>. <b>Import now</b> resumes incrementally from each environment's cursor; <b>Backfill now</b> re-scans the whole range in resumable chunks.</p>`}
function sourcePanel(){const s=sourceHealth; const disabled=s?.health==='disabled'; const disAttr=disabled?'disabled title="Enable the Langfuse integration above to import."':''; return `<section class="panel"><h2>AI evidence source (Langfuse)</h2>${s?`<p>State: <b>${esc(s.health)}</b> — ${esc(s.message)}</p><p>Source: ${esc(s.source)} · Base URL: <code>${esc(s.base_url)}</code> · Environments: ${esc(s.environments.join(', ')||'—')}</p><p>Last import: ${esc(s.last_import_at||'never')} · Latest trace: ${esc(s.latest_trace_ts||'—')}</p>`:'<p>Source health is unavailable.</p>'}<p>Vire reads AI time, usage, and cost from local Docker self-hosted Langfuse on loopback. A down stack is reported as unavailable, never as zero usage or cost.</p>${runtimeLine()}${renderImportReport(lastImportReport,lastImportMode)}${rangeControl()}<div class="row"><button id="importLangfuse" ${disAttr}>Import from Langfuse now</button><button id="backfillLangfuse" ${disAttr}>Backfill now</button></div></section>`}
function table(rows:Entry[], actions=false){return `<table><tr><th>Date</th><th>Project</th><th>Start</th><th>End</th><th>Duration</th><th>Note</th>${actions?'<th></th>':''}</tr>${rows.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.project_name)}</td><td>${esc(e.start_time)}</td><td>${esc(e.end_time)}</td><td>${esc(h(e.duration_minutes))}</td><td>${esc(e.note||'')}</td>${actions?`<td><button data-edite="${esc(e.id)}">Edit</button> <button class="danger" data-del="${esc(e.id)}">Delete</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${actions?7:6}" class="empty">No entries found.</td></tr>`}</table>`}
rerender();
